// examples/ui/StringFilter.tsx
/** @jsxImportSource react */
import {
	type KeyboardEvent,
	memo,
	type ReactElement,
	type SyntheticEvent,
	useCallback,
} from "react";

type StringFilterProps = Readonly<{
	name: string;
	value?: unknown;
	setFilterValue: (filterName: string, value: unknown) => void;
	resetFilter: (filterName: string) => void;
	applyFilter: (filterName: string) => void;
}>;

function StringFilterInner({
	name,
	value = undefined,
	setFilterValue,
	resetFilter,
	applyFilter,
}: StringFilterProps): ReactElement {
	const onChange = useCallback(
		(event: SyntheticEvent) => {
			setFilterValue(name, (event.target as HTMLInputElement).value);
		},
		[name, setFilterValue],
	);

	const onKeyDown = useCallback(
		(event: KeyboardEvent) => {
			if (event.key === "Enter") {
				applyFilter(name);
			}
		},
		[name, applyFilter],
	);

	const onApplyClick = useCallback(() => {
		applyFilter(name);
	}, [name, applyFilter]);

	const onResetClick = useCallback(() => {
		resetFilter(name);
	}, [name, resetFilter]);

	const id = `id_${name}`;

	return (
		<div className="field-row">
			<div
				style={{
					flex: 1,
				}}
			>
				<label htmlFor={id}>{name}</label>

				<div className="field-row">
					<input
						id={id}
						type="text"
						name={name}
						value={typeof value === "string" ? value : ""}
						onChange={onChange}
						onKeyDown={onKeyDown}
						style={{
							flex: 1,
						}}
					/>

					<button type="button" onClick={onApplyClick}>
						Apply
					</button>

					<button type="button" onClick={onResetClick}>
						Reset
					</button>
				</div>
			</div>
		</div>
	);
}

export const StringFilter = memo(StringFilterInner);

// packages/qwik-filterlist-example/src/ui/StringFilter.tsx
/** @jsxImportSource @builder.io/qwik */
import { type QRL, component$ } from "@builder.io/qwik";
import { clsx } from "clsx";
import buttonStyles from "./Button.module.css";
import styles from "./StringFilter.module.css";

type StringFilterProps = Readonly<{
	name: string;
	value?: unknown;
	setFilterValue$: QRL<(filterName: string, value: unknown) => void>;
	resetFilter$: QRL<(filterName: string) => Promise<void>>;
	applyFilter$: QRL<(filterName: string) => Promise<void>>;
}>;

export const StringFilter = component$(
	({
		name,
		value = undefined,
		setFilterValue$,
		resetFilter$,
		applyFilter$,
	}: StringFilterProps) => {
		return (
			<div class={styles.wrapper}>
				<div class={styles.name}>{name}</div>

				<div class={styles.inputWrapper}>
					<input
						class={styles.input}
						name={name}
						value={typeof value === "string" ? value : ""}
						onChange$={(event) => {
							setFilterValue$(name, (event.target as HTMLInputElement).value);
						}}
						onKeyDown$={(event) => {
							if (event.key === "Enter") {
								applyFilter$(name);
							}
						}}
					/>
				</div>

				<div class={styles.buttonWrapper}>
					<button
						class={buttonStyles.button}
						type="button"
						onClick$={() => {
							applyFilter$(name);
						}}
					>
						Apply
					</button>
				</div>

				<div class={styles.buttonWrapper}>
					<button
						class={clsx(buttonStyles.button, buttonStyles.buttonDanger)}
						type="button"
						onClick$={() => {
							resetFilter$(name);
						}}
					>
						Reset
					</button>
				</div>
			</div>
		);
	},
);
