// examples/ui/Table.tsx
/** @jsxImportSource react */
import { type ReactElement, memo } from "react";
import type { Sort } from "../../packages/filterlist/src/types";
import type { User } from "../types";
import { Th } from "./Th";

type TableProps = Readonly<{
	sort: Sort;
	items: readonly User[];
	setSorting: (param: string) => void;
}>;

function TableInner({ sort, items, setSorting }: TableProps): ReactElement {
	return (
		<table
			style={{
				width: "100%",
			}}
		>
			<thead>
				<tr>
					<Th
						param="id"
						current={sort.param}
						asc={sort.asc}
						setSorting={setSorting}
					>
						id
					</Th>

					<Th
						param="name"
						current={sort.param}
						asc={sort.asc}
						setSorting={setSorting}
					>
						name
					</Th>

					<Th
						param="email"
						current={sort.param}
						asc={sort.asc}
						setSorting={setSorting}
					>
						email
					</Th>

					<Th
						param="city"
						current={sort.param}
						asc={sort.asc}
						setSorting={setSorting}
					>
						city
					</Th>
				</tr>
			</thead>

			<tbody>
				{items.map(({ id, name, email, city }) => (
					<tr key={id}>
						<td>{id}</td>
						<td>{name}</td>
						<td>{email}</td>
						<td>{city}</td>
					</tr>
				))}
			</tbody>
		</table>
	);
}

export const Table = memo(TableInner);

// packages/qwik-filterlist-example/src/ui/Table.tsx
/** @jsxImportSource @builder.io/qwik */
import { type QRL, component$ } from "@builder.io/qwik";
import type { User } from "../../../../examples/types";
import type { Sort } from "../../../filterlist/src/types";
import styles from "./Table.module.css";
import { Th } from "./Th";

type TableProps = Readonly<{
	sort: Sort;
	items: readonly User[];
	setSorting$: QRL<(param: string) => void>;
}>;

export const Table = component$(({ sort, items, setSorting$ }: TableProps) => {
	return (
		<table class={styles.table}>
			<thead>
				<tr>
					<Th
						param="id"
						current={sort.param}
						asc={sort.asc}
						setSorting$={setSorting$}
					>
						id
					</Th>

					<Th
						param="name"
						current={sort.param}
						asc={sort.asc}
						setSorting$={setSorting$}
					>
						name
					</Th>

					<Th
						param="email"
						current={sort.param}
						asc={sort.asc}
						setSorting$={setSorting$}
					>
						email
					</Th>

					<Th
						param="city"
						current={sort.param}
						asc={sort.asc}
						setSorting$={setSorting$}
					>
						city
					</Th>
				</tr>
			</thead>

			<tbody>
				{items.map(({ id, name, email, city }) => (
					<tr key={id}>
						<td class={styles.td}>{id}</td>
						<td class={styles.td}>{name}</td>
						<td class={styles.td}>{email}</td>
						<td class={styles.td}>{city}</td>
					</tr>
				))}
			</tbody>
		</table>
	);
});
