// examples/ui/Th.tsx
/** @jsxImportSource react */
import { type ReactElement, type ReactNode, memo, useCallback } from "react";

type ThProps = Readonly<{
	asc?: boolean;
	children?: ReactNode;
	current?: string | null;
	param: string;
	setSorting: (param: string) => void;
}>;

function ThInner({
	param,

	current = null,
	asc = undefined,

	children = undefined,

	setSorting,
}: ThProps): ReactElement {
	const onClick = useCallback((): void => {
		setSorting(param);
	}, [param, setSorting]);

	return (
		<th onClick={onClick} role="button" tabIndex={0}>
			{children}

			{param === current && (asc ? "↓" : "↑")}
		</th>
	);
}

export const Th = memo(ThInner);

// packages/qwik-filterlist-example/src/ui/Th.tsx
/** @jsxImportSource @builder.io/qwik */
import { type QRL, Slot, component$ } from "@builder.io/qwik";
import styles from "./Th.module.css";

type ThProps = Readonly<{
	asc?: boolean;
	current?: string | null;
	param: string;
	setSorting$: QRL<(param: string) => void>;
}>;

export const Th = component$(
	({
		param,

		current = null,
		asc = undefined,

		setSorting$,
	}: ThProps) => {
		return (
			<th
				class={styles.th}
				onClick$={(): void => {
					setSorting$(param);
				}}
			>
				<Slot />

				{param === current && (asc ? "↓" : "↑")}
			</th>
		);
	},
);
