// packages/qwik-filterlist-example/src/ui/ItemsPerPage.tsx
/** @jsxImportSource @builder.io/qwik */
import { type QRL, component$ } from "@builder.io/qwik";
import styles from "./ItemsPerPage.module.css";

type ItemsPerPageProps = Readonly<{
	value: number;
	setPageSize$: QRL<(pageSize: number | null | undefined) => Promise<void>>;
}>;

export const ItemsPerPage = component$(
	({ value, setPageSize$ }: ItemsPerPageProps) => {
		return (
			<div class={styles.wrapper}>
				<div class={styles.text}>Items per page</div>

				<select
					class={styles.select}
					value={value}
					onChange$={(event) => {
						setPageSize$(Number((event.target as HTMLInputElement).value));
					}}
				>
					<option value="10">10</option>
					<option value="20">20</option>
					<option value="30">30</option>
				</select>
			</div>
		);
	},
);

// examples/ui/ItemsPerPage.tsx
/** @jsxImportSource react */
import {
	memo,
	type ReactElement,
	type SyntheticEvent,
	useCallback,
} from "react";

type ItemsPerPageProps = Readonly<{
	value: number;
	setPageSize: (pageSize: number | null | undefined) => void;
}>;

function ItemsPerPageInner({
	value,
	setPageSize,
}: ItemsPerPageProps): ReactElement {
	const onChange = useCallback(
		(event: SyntheticEvent) => {
			setPageSize(Number((event.target as HTMLInputElement).value));
		},
		[setPageSize],
	);

	return (
		<div className="field-row">
			<span>Items per page</span>

			<select value={value} onChange={onChange}>
				<option value="10">10</option>
				<option value="20">20</option>
				<option value="30">30</option>
			</select>
		</div>
	);
}

export const ItemsPerPage = memo(ItemsPerPageInner);
