// packages/qwik-filterlist-example/src/ui/Page.tsx
/** @jsxImportSource @builder.io/qwik */
import { type QRL, component$ } from "@builder.io/qwik";
import { qwikify$ } from "@builder.io/qwik-react";
import type { ListState } from "@vtaits/filterlist";
import { Paginator as ReactPaginator } from "@vtaits/react-paginator";
import type { Additional, User } from "../../../../examples/types";
import buttonStyles from "./Button.module.css";
import { Filters } from "./Filters";
import { ItemsPerPage } from "./ItemsPerPage";
import styles from "./Page.module.css";
import { Preloader } from "./Preloader";
import { Table } from "./Table";
import { TotalCount } from "./TotalCount";

const Paginator = qwikify$(ReactPaginator);

type PageProps = Readonly<{
	listState: ListState<User, Additional, unknown>;
	setFilterValue$: QRL<(filterName: string, value: unknown) => void>;
	resetFilter$: QRL<(filterName: string) => Promise<void>>;
	applyFilter$: QRL<(filterName: string) => Promise<void>>;
	setPage$: QRL<(page: number) => Promise<void>>;
	setPageSize$: QRL<(pageSize: number | null | undefined) => Promise<void>>;
	resetAllFilters$: QRL<() => Promise<void>>;
	reload$: QRL<() => Promise<void>>;
	setSorting$: QRL<(param: string, asc?: boolean) => void>;
	isInfinity?: boolean;
	loadMore$?: QRL<() => void>;
}>;

export const Page = component$(
	({
		listState,
		resetAllFilters$,
		reload$,
		setFilterValue$,
		resetFilter$,
		applyFilter$,
		setPage$,
		setPageSize$,
		setSorting$,
		isInfinity = false,
		loadMore$ = undefined,
	}: PageProps) => {
		const {
			loadedPages,
			filters,
			page,
			pageSize: pageSizeProp = null,
			sort,
			items,
			total = undefined,
			loading,
		} = listState;

		const pageSize = pageSizeProp || 10;

		return (
			<div class={styles.wrapper}>
				<div class={styles.view}>
					<Filters
						filters={filters}
						resetAllFilters$={resetAllFilters$}
						setFilterValue$={setFilterValue$}
						resetFilter$={resetFilter$}
						applyFilter$={applyFilter$}
						reload$={reload$}
					/>

					<div class={styles.totalCount}>
						{total && <TotalCount count={total} />}
					</div>

					<Table items={items} sort={sort} setSorting$={setSorting$} />

					{loading && <Preloader />}

					<div class={styles.bottomBlock}>
						{isInfinity ? (
							<button
								class={buttonStyles.button}
								type="button"
								onClick$={loadMore$}
								disabled={!total || Math.ceil(total / pageSize) === loadedPages}
							>
								Load more
							</button>
						) : (
							<>
								<div>
									{typeof total === "number" && total > 0 && (
										<Paginator
											page={page}
											pageCount={Math.ceil(total / pageSize)}
											onPageChange$={setPage$}
										/>
									)}
								</div>

								<ItemsPerPage value={pageSize} setPageSize$={setPageSize$} />
							</>
						)}
					</div>
				</div>

				<div class={styles.listStateWrapper}>
					<div class={styles.listStateTitle}>Current state of filterlist:</div>

					<pre class={styles.listState}>
						{JSON.stringify(listState, null, 2)}
					</pre>
				</div>
			</div>
		);
	},
);

// examples/ui/Page.tsx
import { type ReactElement, useCallback } from "react";

import styled from "styled-components";

import { Paginator } from "@vtaits/react-paginator";

import { Button } from "./Button";
import { Filters } from "./Filters";
import { ItemsPerPage } from "./ItemsPerPage";
import { Preloader } from "./Preloader";
import { Table } from "./Table";
import { TotalCount } from "./TotalCount";

import type { Additional, User } from "../types";

import type { ListState, Sort } from "../../packages/filterlist/src/types";

type PageProps = Readonly<{
	listState: ListState<User, Additional, unknown>;
	filters: Readonly<Record<string, unknown>>;
	page: number;
	pageSize?: number | null;
	sort: Sort;
	items: readonly User[];
	total?: number | null;
	loading: boolean;
	setFilterValue: (filterName: string, value: unknown) => void;
	resetFilter: (filterName: string) => Promise<void>;
	applyFilter: (filterName: string) => Promise<void>;
	setPage: (page: number) => Promise<void>;
	setPageSize: (pageSize: number | null | undefined) => Promise<void>;
	resetAllFilters: () => Promise<void>;
	reload: () => Promise<void>;
	setSorting: (param: string) => void;
	isInfinity?: boolean;
	loadMore?: () => void;
}>;

const StyledWrapper = styled.div({
	display: "flex",
	alignItems: "flex-start",
});

const StyledView = styled.div({
	maxWidth: 900,
});

const StyledListStateWrapper = styled.div({
	paddingLeft: 40,
});

const StyledListStateTitle = styled.div({
	fontSize: 24,
	lineHeight: 1.2,
	marginBottom: 20,
});

const StyledListState = styled.pre({
	boxSizing: "border-box",
	backgroundColor: "#efefef",
	width: 600,
	height: 600,
	padding: 15,
	overflow: "auto",
});

const StyledTotalCountBlock = styled.div({
	marginBottom: 20,
	height: 22,
});

const StyledBottomBlock = styled.div({
	display: "flex",
	justifyContent: "space-between",
	marginTop: 30,
});

export function Page({
	listState,
	filters,
	page,
	pageSize: pageSizeProp = null,
	sort,
	items,
	total = undefined,
	loading,
	resetAllFilters,
	reload,
	setFilterValue,
	resetFilter,
	applyFilter,
	setPage,
	setPageSize,
	setSorting,
	isInfinity = false,
	loadMore = undefined,
}: PageProps): ReactElement {
	const { loadedPages } = listState;

	const pageSize = pageSizeProp || 10;

	return (
		<StyledWrapper>
			<StyledView>
				<Filters
					filters={filters}
					resetAllFilters={resetAllFilters}
					setFilterValue={setFilterValue}
					resetFilter={resetFilter}
					applyFilter={applyFilter}
					reload={reload}
				/>

				<StyledTotalCountBlock>
					{total && <TotalCount count={total} />}
				</StyledTotalCountBlock>

				<Table items={items} sort={sort} setSorting={setSorting} />

				{loading && <Preloader />}

				<StyledBottomBlock>
					{isInfinity ? (
						<Button
							type="button"
							onClick={loadMore}
							disabled={!total || Math.ceil(total / pageSize) === loadedPages}
						>
							Load more
						</Button>
					) : (
						<>
							<div>
								{total && total > 0 && (
									<Paginator
										page={page}
										pageCount={Math.ceil(total / pageSize)}
										onPageChange={setPage}
									/>
								)}
							</div>

							<ItemsPerPage
								value={pageSize}
								setPageSize={setPageSize}
							/>
						</>
					)}
				</StyledBottomBlock>
			</StyledView>

			<StyledListStateWrapper>
				<StyledListStateTitle>
					Current state of filterlist:
				</StyledListStateTitle>

				<StyledListState>{JSON.stringify(listState, null, 2)}</StyledListState>
			</StyledListStateWrapper>
		</StyledWrapper>
	);
}
