// packages/qwik-filterlist-example/src/ui/Preloader.tsx
/** @jsxImportSource @builder.io/qwik */
import { component$ } from "@builder.io/qwik";
import { qwikify$ } from "@builder.io/qwik-react";
import { definition as faSpinner } from "@fortawesome/free-solid-svg-icons/faSpinner";
import { FontAwesomeIcon as ReactFontAwesomeIcon } from "@fortawesome/react-fontawesome";
import styles from "./Preloader.module.css";

const FontAwesomeIcon = qwikify$(ReactFontAwesomeIcon);

export const Preloader = component$(() => {
	return (
		<div class={styles.preloader}>
			<FontAwesomeIcon icon={faSpinner} pulse size="2x" />
		</div>
	);
});

// examples/ui/Preloader.tsx
import { definition as faSpinner } from "@fortawesome/free-solid-svg-icons/faSpinner";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
/** @jsxImportSource react */
import type { ReactElement } from "react";
import styles from "./Preloader.module.css";

export function Preloader(): ReactElement {
	return (
		<div className={styles.preloader}>
			<FontAwesomeIcon icon={faSpinner} pulse size="2x" />
		</div>
	);
}
