// packages/qwik-filterlist-example/src/ui/TotalCount.tsx
/** @jsxImportSource @builder.io/qwik */
import { component$ } from "@builder.io/qwik";
import styles from "./TotalCount.module.css";

type TotalCountProps = Readonly<{
	count: number;
}>;

export const TotalCount = component$(({ count }: TotalCountProps) => {
	return <div class={styles.totalCount}>Total: {count}</div>;
});

// examples/ui/TotalCount.tsx
/** @jsxImportSource react */
import type { ReactElement } from "react";

import styled from "styled-components";

const StyledWrapper = styled.div({
	fontSize: 18,
	lineHeight: 1.2,
});

type TotalCountProps = {
	readonly count: number;
};

export function TotalCount({ count }: TotalCountProps): ReactElement {
	return <StyledWrapper>Total: {count}</StyledWrapper>;
}
